linting stuff

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -30,21 +30,25 @@ jobs:
       - name: "Set Go version and paths"
         uses: actions/setup-go@v2
         with:
-          go-version: "^1.16.3"
+          go-version: "^1.18.0"
+
+      - name: "Install extra tools"
+        run: |
+          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
 
       - name: "Check code & lint"
         run: make lint
 
       - name: "Run all unit tests"
-        run: make test-reports
+        run: make test
 
       # Very optional - upload of test results
-      - name: "Upload test reports to Azure"
-        if: ${{ success() || failure() }}
-        run: |
-          az storage blob upload-batch --account-name $STORAGE_ACCT_NAME --account-key "${{ secrets.STORAGE_KEY }}" \
-             --source ./output --destination \$web/${{ github.run_id }} --no-progress > /dev/null
-          echo -e "📜🌍 Test reports uploaded and viewable here - https://$STORAGE_ACCT_NAME.z6.web.core.windows.net/${{ github.run_id }}/"
+      # - name: "Upload test reports to Azure"
+      #   if: ${{ success() || failure() }}
+      #   run: |
+      #     az storage blob upload-batch --account-name $STORAGE_ACCT_NAME --account-key "${{ secrets.STORAGE_KEY }}" \
+      #        --source ./output --destination \$web/${{ github.run_id }} --no-progress > /dev/null
+      #     echo -e "📜🌍 Test reports uploaded and viewable here - https://$STORAGE_ACCT_NAME.z6.web.core.windows.net/${{ github.run_id }}/"
 
   # ===== Build container images ======
   build-images:
